#!/usr/bin/env python  
import roslib
roslib.load_manifest('ur10e_e_moveit_config')
import rospy
import tf
from geometry_msgs.msg import PoseStamped

class TF_publish(object):
    def __init__(self):
        rospy.init_node('turtle_tf_broadcaster')
        rate = rospy.Rate(10.0)
		target = PoseStamped()
        listener = tf.TransformListener()
        broadcaster = tf.TransformBroadcaster()
        while not rospy.is_shutdown():
        	try:
        		self.object_target = listener.lookupTransform('camera_link', 'test', rospy.Time(0))
        	except (tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException):
            	continue
        pub = tr.TransformBroadcaster()
        pub.sendTransform((object_target.pose.position.x, object_target.pose.position.y, object_target.pose.position.z),
                        (object_target.pose.rotation.x, object_target.pose.rotation.y, object_target.pose.rotation.z, object_target.pose.rotation.w),rospy.Time.now(),"object","camer_link")
        rospy.spin()

if __name__ == '__main__':
operation = TF_publish()